# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: |
      source build.sh && source publish_website.sh
    env:
      SURGE_LOGIN: $(SURGE_LOGIN)
      SURGE_TOKEN: $(SURGE_TOKEN)
- job: Mac
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - bash: |
      source build.sh 
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - bash: |
      source common.sh && source build.sh
