# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops

jobs:
# Linux VM fails building because of: https://github.com/mono/mono/issues/13537
#- job: Linux
#  pool:
#    vmImage: 'ubuntu-16.04'
#  steps:
#  - bash: |
#      ./build.sh
#    env:
#      SURGE_LOGIN: $(SURGE_LOGIN)
#      SURGE_TOKEN: $(SURGE_TOKEN)
- job: Mac
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - bash: |
      ./build.sh && ./publish_website.sh
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - bash: |
      ./build.sh