jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      printenv
      ./build.sh 
      ./publish_website.sh
    env:
      SURGE_LOGIN: $(SURGE_LOGIN)
      SURGE_TOKEN: $(SURGE_TOKEN)
- job: Mac
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: |
      printenv
      ./build.sh 
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: |
      bash ./scripts/install_env_windows.sh
      bash ./build.sh
      