jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: |
      bash printenv
      bash ./scripts/install_env_windows.sh
      bash ./build.sh
      bash ./publish_website.sh
      
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      printenv
      ./build.sh 

- job: Mac
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: |
      printenv
      ./build.sh 