jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: |
      echo TODO

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      ./build.sh

- job: Mac
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: |
      ./build.sh