jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      echo TODO

- job: Linux
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - script: |
      ./build.sh

- job: Mac
  pool:
    vmImage: 'macOS 10.13'
  steps:
  - script: |
      ./build.sh